### ISSUE TITLE
core dumped

### ISSUE THREAD

**Issue by wyx518** [bbbbbback/machine-reading#1]
![图片](https://user-images.githubusercontent.com/26063832/57203946-c16fc680-6fe6-11e9-90ce-c93ce4a1b259.png)
运行代码的时候会出现这个错误，是哪个部分出现了问题吗

**Comment by RomanShen** [comment]
你好，我没有遇到这个问题。可以参考一下https://www.jianshu.com/p/8f8cc499fee1
或许有用。或者把训练集的样本删掉一点，debug一下试试看。
https://github.com/NoviScl/BERT-RACE
这个是race在bert上直接微调的代码，你也可以试试。这个代码的结果是可以复现的。

**Comment by RomanShen** [comment]
你好，我没有遇到这个问题。可以参考一下https://www.jianshu.com/p/8f8cc499fee1
或许有用。或者把训练集的样本删掉一点，debug一下试试看。
https://github.com/NoviScl/BERT-RACE
这个是race在bert上直接微调的代码，你也可以试试。这个代码的结果是可以复现的。

**Comment by wyx518** [comment]
网上搜到的方法几乎都试过了，没有用处
在https://github.com/NoviScl/BERT-RACE跑会出现同样的报错，会是因为GPU的问题吗，还是说RACE的数据集太大？

**Comment by RomanShen** [comment]
应该不是GPU的问题，可能是内存的问题。建议试试huggingface的pytorch里的extract_features，这个要求很低。

**Comment by wyx518** [comment]
用BERT跑SQUAD都是可以跑的，所以才会觉得是RACE数据集太大，准备试试用一半训练集看可以跑吗

**Comment by wyx518** [comment]
问题依然没有解决，发现应该是apex的问题，torch version 1.0.1，apex==0.1？

**Comment by wyx518** [comment]
终于把问题解决了，是APEX安装时的问题，Ubuntu14.04默认的GCC版本是4.8 但是APEX安装需要4.9以上版本才能正确使用fusedlayernorm。
